### ISSUE TITLE
[1.19.2]  Random crash while roaming overworld

### ISSUE THREAD

**Issue by Reshy** [CCr4ft3r/DimensionalThreading-Reforged#13]
[20Aug2023 21:45:49.052] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:29) ~[Dimensional-Threading-Reforged-1.19.2-1.2.8.jar%23572!/:1.19.2-1.2.8]
	at net.minecraft.server.MinecraftServer.handler$fho000$tickWorlds(MinecraftServer.java:6474) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:851) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 2 but got 1. Expected types were [net.minecraft.world.entity.EntityType, net.minecraft.world.level.Level], actual types were [net.minecraft.server.level.ServerLevel].
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationRuntime.checkArgumentCount(WrapOperationRuntime.java:10) ~[MixinExtras-0.2.0-beta.9.jar%23853!/:?]
	at net.minecraft.server.level.ServerLevel.mixinextras$bridge$0$m_20615_(ServerLevel.java) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.level.ServerLevel.wrapOperation$gpo000$replaceLightningBolt(ServerLevel.java:14721) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:403) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:360) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at net.minecraft.server.MinecraftServer.mdd58816$lambda$tickWorlds$0$3(MinecraftServer.java:6463) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:51) ~[Dimensional-Threading-Reforged-1.19.2-1.2.8.jar%23572!/:1.19.2-1.2.8]
	at net.minecraft.server.MinecraftServer.mdd58816$lambda$tickWorlds$1$2(MinecraftServer.java:6460) ~[client-1.19.2-20220805.130853-srg.jar%23803!/:?]
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49) ~[JavaUtils-bd58640372.jar%23869!/:?]
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43) ~[JavaUtils-bd58640372.jar%23869!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more

Crash Log:  https://pastebin.com/hVa8Am0h

**Comment by SrRapero720** [comment]
Your issue is caused by other mod using MixinExtra, nothing related to DImThreads. 
check cause of the crash 
`Caused by: com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 2 but got 1. Expected types were [net.minecraft.world.entity.EntityType, net.minecraft.world.level.Level], actual types were [net.minecraft.server.level.ServerLevel].`

Basically all suspected mods are
- forgeendertech
- sereneseasons
- modernfix
- supplementaries
- citadel
- ysns
- pluto
- immersive_weathering
- corgilib
- canary
- observable
- biomemakeover
- betterdeserttemples
- blueprint
- rottencreatures
- enhancedcelestials
- sound_physics_remastered
- create (maybe not)
- fabrication
- midnight config

try removing one by one to get witch mod is causing it, and don't forget to report it to the creator of the mod :)
