### ISSUE TITLE
[1.18.2]Crash on world loaded.

### ISSUE THREAD

**Issue by Tollainmear** [CCr4ft3r/DimensionalThreading-Reforged#17]
Hi, I got game crashes when loaded both this mod and the GlobalGamerules mod, it looks like they are not compatible.

here is the crash report below:
```
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "wearblackallday.util.ThreadPool.getActiveCount()" because "current" is null
	at wearblackallday.dimthread.util.ServerManager.setThreadCount(ServerManager.java:50) ~[%5B维度优化%5DDimensional-Threading-Reforged-1.18.2-1.2.8.jar%23258!/:1.18.2-1.2.8] {re:mixin,re:classloading}
	at net.minecraft.world.level.GameRules$Value.m_46368_(GameRules.java:274) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.GameRules$Value.m_46370_(GameRules.java:269) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at se.gory_moon.globalgamerules.WorldEvents.lambda$onWorldLoad$2(WorldEvents.java:74) ~[%5B全局游戏规则%5D%20GlobalGameRules-1.18.2-6.0.1.8.jar%23117!/:6.0.1.8] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at se.gory_moon.globalgamerules.WorldEvents.onWorldLoad(WorldEvents.java:74) ~[%5B全局游戏规则%5D%20GlobalGameRules-1.18.2-6.0.1.8.jar%23117!/:6.0.1.8] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2_WorldEvents_onWorldLoad_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:361) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:dimthread.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:316) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:dimthread.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:64) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?] {re:mixin,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:runtimedistcleaner:A,re:computing_frames,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:runtimedistcleaner:A,re:classloading,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:dimthread.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:dimthread.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
```

I don't know if it is a problem of Dimensional Threading reforged or Global Gamerules? But can you help to fix that?

thx ! : )

**Comment by CCr4ft3r** [comment]
Seems to be like an incompatibility caused by DimThread. 
Fixing it will take some time because of time issues.
